### PR TITLE
Changed \String::* calls to \StringUtil for PHP7 compatibility reasons

### PR DESCRIPTION
**Pull request by bytehead**
PHP 7 compatibility - see contao/core-bundle#309.

### CODE REVIEW

**Comment by bytehead** [comment]
There is some other stuff to be fixed for PHP7:

```bash
File:system/modules/syncCto/SyncCtoFiles.php
> Line 1511: Indirect variable, property or method access
    $this->{$arrCallback[0]}->{$arrCallback[1]}();
> Line 1511: Indirect variable, property or method access
    $this->{$arrCallback[0]};
> Line 1524: Indirect variable, property or method access
    $this->{$arrCallback[0]}->{$arrCallback[1]}();
> Line 1524: Indirect variable, property or method access
    $this->{$arrCallback[0]};
> Line 1542: Indirect variable, property or method access
    $this->{$arrCallback[0]}->{$arrCallback[1]}();
> Line 1542: Indirect variable, property or method access
    $this->{$arrCallback[0]};
> Line 1562: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}($arrSettings);
> Line 1562: Indirect variable, property or method access
    $this->{$callback[0]};


File: system/modules/syncCto/SyncCtoHelper.php
> Line 782: Indirect variable, property or method access
    $this->{$callback[0]}->{$callback[1]}();
> Line 782: Indirect variable, property or method access
    $this->{$callback[0]};


File: system/modules/syncCto/SyncCtoModuleClient.php
> Line 2775: Indirect variable, property or method access
    $objCallbackClass->{$callback[1]}($this->intClientID, $this->arrSyncSettings['syncCto_SyncTables'], $arrSQL);
> Line 2842: Indirect variable, property or method access
    $objCallbackClass->{$callback[1]}($this->intClientID, $arrSQL);
> Line 3405: Indirect variable, property or method access
    $objCallbackClass->{$arrCurrentFunction[1]}($this, $this->intClientID);
> Line 4850: Indirect variable, property or method access
    $objCallbackClass->{$callback[1]}($this->intClientID, $this->arrSyncSettings['syncCto_SyncTables'], $arrSQL);
```

**Comment by bytehead** [comment]
Update version with correct version compare (inclusive `BUILD` number). See [comment](https://github.com/contao-community-alliance/events-contao-bindings/pull/10#discussion_r52897571) from @discordier.

**Comment by stefanheimes** [comment]
Thanks for the PR.

**Comment by bytehead** [comment]
No worries, thanks for merging!
Should I provide another PR for the [missing changes](https://github.com/menatwork/syncCto/pull/260#issuecomment-182390556) in the comment above?

**Comment by stefanheimes** [comment]
Sure, if u have the time. I am happy if someone helps.

The PR is available in version 3.2.0-beta4.

**Pull request merged**
